name: basis
description: A package for scaffolding Flutter apps basis
version: 1.0.0-legacy
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter:

dependencies:
  flutter:
    sdk: flutter
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: